on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

name: Test-study-package

jobs:
  Test-module:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rspm: "https://cloud.r-project.org"}
          - {os: macOS-latest, r: 'release', rspm: "https://cloud.r-project.org"}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/latest"}

    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RENV_CONFIG_REPOS_OVERRIDE: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install system requirements
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y make
          sudo apt-get install -y default-jdk
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libssl-dev

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
